# Generated by Django 5.0.4 on 2024-04-07 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="bodyarea",
            new_name="body_area",
        ),
    ]
