# Generated by Django 5.0.4 on 2024-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_bodyarea_note_body_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body_area",
            field=models.CharField(max_length=20),
        ),
    ]
