# Generated by Django 5.0.4 on 2024-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_note_body_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body_area",
            field=models.CharField(
                choices=[
                    ("Full Body", "full-body"),
                    ("Legs", "legs"),
                    ("Abs", "abs"),
                    ("Chest", "chest"),
                    ("Back", "back"),
                    ("Shoulders", "shoulders"),
                    ("Arms", "arms"),
                ],
                default="Full Body",
                max_length=20,
            ),
        ),
    ]
