# Generated by Django 5.0.4 on 2024-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_note_body_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="body_area",
        ),
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(default="Category", max_length=100),
        ),
    ]
