# Generated by Django 5.0.4 on 2024-04-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_note_body_area_note_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
